const refs = {
  months: [
    'січень',
    'лютий',
    'березень',
    'квітень',
    'травень',
    'червень',
    'липень',
    'серпень',
    'вересень',
    'жовтень',
    'листопад',
    'грудень',
  ],
  departments: ['СРМ', 'СП', 'СЛЕП', 'СРЗА', 'СДІЗП', 'МС', 'ЦРЕУ', 'ВТС'],
  headers: [
    'FISTL',
    'NAME_FISTL',
    'NAME_ORG',
    'ZZBSTKD',
    'BSTDK',
    'VID_PLAT',
    'WRBTR',
    'WRBTR1',
    'SUM1',
    'SUM2',
    'SUM3',
    'SUM4',
    'SUM5',
    'Количество',
    'b',
    'Цена',
    'proc',
    'с',
    'блок',
  ],
};

export default refs;
